version: '3.8'
services:
  mongodb: 
    container_name: mymongo
    image: mongo
    restart: unless-stopped
    env_file:
      - mongo.env
    volumes: 
      - ./.docker/mongodb/data/db/:/data/db/ 
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    networks:
      - backend-network 
    environment:
      - MONGO_INITDB_ROOT_USERNAME: MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD: MONGO_PASSWORD
      - MONGO_INITDB_DATABASE: DB
    ports: 
      - 27017:27017

  web:
    container_name: flask
    build: flask
    restart: always
    env_file:
      - mongo.env
      - flask.env
    volumes:
      - ./flask:/flask
    ports:
      - 5000:5000
    networks:
      - backend-network
      - frontend-network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: unless-stopped
    env_file:
      - nginx.env
    volumes:
      - nginx-secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend-network
    depends_on:
      - web

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - frontend-network

volumes:
  nginx-secrets:  
  mongodb:

networks:
  backend-network:
  frontend-network: